# Generated by Django 2.0.6 on 2018-06-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0003_goods_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
